db.getCollection('ELPModel').insert([
{
    "_class" : "com.zqykj.hyjj.entity.elp.ElpModel",
    "modelId" : "standard_model",
    "uuid" : "standard_model",
    "version" : 0,
    "entities" : [
    {
        "uuid" : "mobile_phone",
        "name" : "手机",
        "semanticType" : "virtual_goods",
        "semanticName" : "虚拟物品",
        "rootSemanticType" : "mobile_phone",
        "idProperty" : {
            "uuid" : "ID",
            "name" : "标识",
            "identifier" : true,
            "type" : "text",
            "index" : true,
            "multivalue" : false,
            "stored" : true,
            "analyse" : false,
            "originType" : "CUSTOM"
        },
        "properties" : [
            {
                "uuid" : "begin_time",
                "name" : "开始时间",
                "semanticType" : "datetime",
                "semanticName" : "日期时间",
                "identifier" : false,
                "type" : "datetime",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "end_time",
                "name" : "结束时间",
                "semanticType" : "datetime",
                "semanticName" : "日期时间",
                "identifier" : false,
                "type" : "datetime",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "src_ipv4",
                "name" : "src_ipv4",
                "semanticType" : "website",
                "semanticName" : "网址",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "CUSTOM"
            },
            {
                "uuid" : "brand",
                "name" : "brand",
                "semanticType" : "brand",
                "semanticName" : "品牌名称",
                "identifier" : false,
                "type" : "text",
                "index" : false,
                "multivalue" : false,
                "stored" : true,
                "analyse" : true,
                "originType" : "CUSTOM"
            },
            {
                "uuid" : "host",
                "name" : "host",
                "semanticType" : "website",
                "semanticName" : "网址",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "CUSTOM"
            },
            {
                "uuid" : "id",
                "name" : "id标识1",
                "semanticType" : "text",
                "semanticName" : "文本",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : true,
                "originType" : "CUSTOM"
            },
            {
                "uuid" : "shu23",
                "name" : "属性1",
                "semanticType" : "text",
                "semanticName" : "文本",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : true,
                "originType" : "CUSTOM"
            },
            {
                "uuid" : "d456g",
                "name" : "属性2",
                "semanticType" : "text",
                "semanticName" : "文本",
                "identifier" : false,
                "type" : "text",
                "index" : false,
                "multivalue" : false,
                "stored" : false,
                "analyse" : false,
                "originType" : "CUSTOM"
            }
        ],
        "labelTemplate" : "id标识1",
        "iconUrl" : "/Telecom/Cellphone.png",
        "lastUpdateTime" : ISODate("2018-05-25T18:34:02.090+08:00")
    },
    {
        "uuid" : "email",
        "name" : "邮箱账号",
        "semanticType" : "email_account",
        "semanticName" : "邮箱账号",
        "rootSemanticType" : "email_account",
        "idProperty" : {
            "uuid" : "ID",
            "name" : "标识",
            "identifier" : true,
            "type" : "text",
            "index" : true,
            "multivalue" : false,
            "stored" : true,
            "analyse" : false,
            "originType" : "CUSTOM"
        },
        "properties" : [
            {
                "uuid" : "begin_time",
                "name" : "开始时间",
                "semanticType" : "datetime",
                "semanticName" : "日期时间",
                "identifier" : false,
                "type" : "datetime",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "end_time",
                "name" : "结束时间",
                "semanticType" : "datetime",
                "semanticName" : "日期时间",
                "identifier" : false,
                "type" : "datetime",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "email_address",
                "name" : "邮箱地址",
                "semanticType" : "email_address",
                "semanticName" : "邮箱",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : true,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "email_type",
                "name" : "邮箱类型",
                "semanticType" : "text",
                "semanticName" : "文本",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "owner_id",
                "name" : "拥有者",
                "semanticType" : "id_card_number",
                "semanticName" : "身份证号",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "CUSTOM"
            },
            {
                "uuid" : "src_ipv4",
                "name" : "src_ipv4",
                "semanticType" : "text",
                "semanticName" : "网址",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : true,
                "originType" : "CUSTOM"
            },
            {
                "uuid" : "host",
                "name" : "host",
                "semanticName" : "网址",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : false,
                "analyse" : false,
                "originType" : "CUSTOM"
            },
            {
                "uuid" : "id",
                "name" : "id标识",
                "semanticType" : "item_id",
                "semanticName" : "物品编号",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "CUSTOM"
            }
        ],
        "labelTemplate" : "id标识",
        "iconUrl" : "/Network/Email.png",
        "lastUpdateTime" : ISODate("2018-05-23T17:46:53.947+08:00")
    },
    {
        "uuid" : "ip",
        "name" : "IP",
        "semanticType" : "virtual_goods",
        "semanticName" : "虚拟物品",
        "rootSemanticType" : "ip",
        "idProperty" : {
            "uuid" : "ID",
            "name" : "标识",
            "identifier" : true,
            "type" : "text",
            "index" : true,
            "multivalue" : false,
            "stored" : true,
            "analyse" : false,
            "originType" : "CUSTOM"
        },
        "properties" : [
            {
                "uuid" : "begin_time",
                "name" : "开始时间",
                "semanticType" : "datetime",
                "semanticName" : "日期时间",
                "identifier" : false,
                "type" : "datetime",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "end_time",
                "name" : "结束时间",
                "semanticType" : "datetime",
                "semanticName" : "日期时间",
                "identifier" : false,
                "type" : "datetime",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "ip",
                "name" : "ipv4",
                "semanticType" : "address_id",
                "semanticName" : "地址编号",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "CUSTOM"
            }
        ],
        "labelTemplate" : "ipv4",
        "iconUrl" : "/Network/IP.png",
        "lastUpdateTime" : ISODate("2018-05-23T17:34:37.959+08:00")
    },
    {
        "uuid" : "pc",
        "name" : "电脑",
        "semanticType" : "goods",
        "semanticName" : "物",
        "rootSemanticType" : "pc",
        "idProperty" : {
            "uuid" : "ID",
            "name" : "标识",
            "identifier" : true,
            "type" : "text",
            "index" : true,
            "multivalue" : false,
            "stored" : true,
            "analyse" : false,
            "originType" : "CUSTOM"
        },
        "properties" : [
            {
                "uuid" : "begin_time",
                "name" : "开始时间",
                "semanticType" : "datetime",
                "semanticName" : "日期时间",
                "identifier" : false,
                "type" : "datetime",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "end_time",
                "name" : "结束时间",
                "semanticType" : "datetime",
                "semanticName" : "日期时间",
                "identifier" : false,
                "type" : "datetime",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "id",
                "name" : "id标识",
                "semanticType" : "item_id",
                "semanticName" : "物品编号",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "CUSTOM"
            },
            {
                "uuid" : "host",
                "name" : "host",
                "semanticType" : "website",
                "semanticName" : "网址",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "CUSTOM"
            }
        ],
        "labelTemplate" : "id标识",
        "iconUrl" : "/Telecom/PC.png",
        "lastUpdateTime" : ISODate("2018-05-25T16:43:59.224+08:00")
    },
    {
        "uuid" : "elp_floating_population_record",
        "name" : "流动人口",
        "semanticType" : "floating_population_record",
        "semanticName" : "流动人口",
        "rootSemanticType" : "people",
        "idProperty" : {
            "uuid" : "ID",
            "name" : "标识",
            "identifier" : true,
            "type" : "text",
            "index" : true,
            "multivalue" : false,
            "stored" : true,
            "analyse" : false,
            "originType" : "CUSTOM"
        },
        "properties" : [
            {
                "uuid" : "begin_time",
                "name" : "开始时间",
                "semanticType" : "datetime",
                "semanticName" : "日期时间",
                "identifier" : false,
                "type" : "datetime",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "end_time",
                "name" : "结束时间",
                "semanticType" : "datetime",
                "semanticName" : "日期时间",
                "identifier" : false,
                "type" : "datetime",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "person_ssn_id",
                "name" : "身份证号",
                "semanticType" : "id_card_number",
                "semanticName" : "身份证号",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "person_name",
                "name" : "姓名",
                "semanticType" : "person_name",
                "semanticName" : "姓名",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : true,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "person_gender",
                "name" : "性别",
                "semanticType" : "text",
                "semanticName" : "文本",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "person_nationality",
                "name" : "国籍",
                "semanticType" : "text",
                "semanticName" : "文本",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "person_ethnicity",
                "name" : "民族",
                "semanticType" : "text",
                "semanticName" : "文本",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "person_height",
                "name" : "身高(CM)",
                "semanticType" : "number",
                "semanticName" : "数字",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "person_bloodtype",
                "name" : "血型",
                "semanticType" : "text",
                "semanticName" : "文本",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "fpr_arrival_date",
                "name" : "来本市日期",
                "semanticType" : "datetime",
                "semanticName" : "日期时间",
                "identifier" : false,
                "type" : "datetime",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "fpr_insurance_status",
                "name" : "参保情况",
                "semanticType" : "text",
                "semanticName" : "文本",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "fpr_profession",
                "name" : "职业",
                "semanticType" : "profession",
                "semanticName" : "职业",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "fpr_household_nature",
                "name" : "户口性质",
                "semanticType" : "household_nature",
                "semanticName" : "户口性质",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "fpr_household_county",
                "name" : "户籍县区",
                "semanticType" : "household_address",
                "semanticName" : "户籍地址",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : true,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "fpr_detail_address",
                "name" : "详址",
                "semanticType" : "address_detail",
                "semanticName" : "详细地址",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : true,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "fpr_living_address",
                "name" : "居住处所",
                "semanticType" : "address_detail",
                "semanticName" : "详细地址",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "fpr_living_reason",
                "name" : "居住事由",
                "semanticType" : "reason",
                "semanticName" : "原因",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "fpr_living_style",
                "name" : "居住方式",
                "semanticType" : "living_style",
                "semanticName" : "居住方式",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "fpr_employer_name",
                "name" : "单位名称",
                "semanticType" : "organization_name",
                "semanticName" : "机构名称",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : true,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "fpr_employer_address",
                "name" : "单位地址",
                "semanticType" : "address_detail",
                "semanticName" : "详细地址",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : true,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "fpr_employer_phone_number",
                "name" : "单位电话",
                "semanticType" : "phone_number",
                "semanticName" : "电话号码",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "fpr_residence_permit_issued",
                "name" : "是否办理居住证",
                "semanticType" : "text",
                "semanticName" : "文本",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "fpr_record_time",
                "name" : "填表时间",
                "semanticType" : "datetime",
                "semanticName" : "日期时间",
                "identifier" : false,
                "type" : "datetime",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "PlqAOe1L8YHhOwbJ",
                "name" : "abcdef",
                "semanticType" : "email_address",
                "semanticName" : "邮箱",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : true,
                "originType" : "CUSTOM"
            }
        ],
        "labelTemplate" : "国籍",
        "iconUrl" : "/SNS/Alitalk.png",
        "lastUpdateTime" : ISODate("2018-05-25T18:09:56.791+08:00")
    },
    {
        "uuid" : "elp_goods_phone",
        "name" : "手机-phone",
        "semanticType" : "goods",
        "semanticName" : "物",
        "rootSemanticType" : "elp_goods_phone",
        "idProperty" : {
            "uuid" : "ID",
            "name" : "标识",
            "identifier" : true,
            "type" : "text",
            "index" : true,
            "multivalue" : false,
            "stored" : true,
            "analyse" : false,
            "originType" : "CUSTOM"
        },
        "properties" : [
            {
                "uuid" : "begin_time",
                "name" : "开始时间",
                "semanticType" : "datetime",
                "semanticName" : "日期时间",
                "identifier" : false,
                "type" : "datetime",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "end_time",
                "name" : "结束时间",
                "semanticType" : "datetime",
                "semanticName" : "日期时间",
                "identifier" : false,
                "type" : "datetime",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "phone_id",
                "name" : "id",
                "semanticType" : "record_id",
                "semanticName" : "记录编号",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "CUSTOM"
            },
            {
                "uuid" : "phone_id_type",
                "name" : "id_type",
                "semanticType" : "text",
                "semanticName" : "文本",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : true,
                "originType" : "CUSTOM"
            }
        ],
        "labelTemplate" : "id",
        "iconUrl" : "/Telecom/Cellphone.png",
        "lastUpdateTime" : ISODate("2018-05-25T23:46:11.358+08:00")
    },
    {
        "uuid" : "elp_goods_mac",
        "name" : "手机-mac",
        "semanticType" : "goods",
        "semanticName" : "物",
        "rootSemanticType" : "elp_goods_mac",
        "idProperty" : {
            "uuid" : "ID",
            "name" : "标识",
            "identifier" : true,
            "type" : "text",
            "index" : true,
            "multivalue" : false,
            "stored" : true,
            "analyse" : false,
            "originType" : "CUSTOM"
        },
        "properties" : [
            {
                "uuid" : "begin_time",
                "name" : "开始时间",
                "semanticType" : "datetime",
                "semanticName" : "日期时间",
                "identifier" : false,
                "type" : "datetime",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "end_time",
                "name" : "结束时间",
                "semanticType" : "datetime",
                "semanticName" : "日期时间",
                "identifier" : false,
                "type" : "datetime",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "mac_id",
                "name" : "id",
                "semanticType" : "record_id",
                "semanticName" : "记录编号",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "CUSTOM"
            },
            {
                "uuid" : "mac_id_type",
                "name" : "id_type",
                "semanticType" : "text",
                "semanticName" : "文本",
                "identifier" : false,
                "type" : "text",
                "index" : false,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "CUSTOM"
            }
        ],
        "labelTemplate" : "id",
        "iconUrl" : "/Telecom/Cellphone.png",
        "lastUpdateTime" : ISODate("2018-05-25T23:53:02.740+08:00")
    },
    {
        "uuid" : "elp_goods_phone_imsi",
        "name" : "手机-imsi",
        "semanticType" : "goods",
        "semanticName" : "物",
        "rootSemanticType" : "elp_goods_phone_imsi",
        "idProperty" : {
            "uuid" : "ID",
            "name" : "标识",
            "identifier" : true,
            "type" : "text",
            "index" : true,
            "multivalue" : false,
            "stored" : true,
            "analyse" : false,
            "originType" : "CUSTOM"
        },
        "properties" : [
            {
                "uuid" : "begin_time",
                "name" : "开始时间",
                "semanticType" : "datetime",
                "semanticName" : "日期时间",
                "identifier" : false,
                "type" : "datetime",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "end_time",
                "name" : "结束时间",
                "semanticType" : "datetime",
                "semanticName" : "日期时间",
                "identifier" : false,
                "type" : "datetime",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "imsi_id",
                "name" : "id",
                "semanticType" : "record_id",
                "semanticName" : "记录编号",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "CUSTOM"
            },
            {
                "uuid" : "imsi_id_type",
                "name" : "id_type",
                "semanticType" : "text",
                "semanticName" : "文本",
                "identifier" : false,
                "type" : "text",
                "index" : false,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "CUSTOM"
            }
        ],
        "labelTemplate" : "id",
        "iconUrl" : "/Telecom/Cellphone.png",
        "lastUpdateTime" : ISODate("2018-05-26T00:12:53.789+08:00")
    }
],
    "links" : [
    {
        "uuid" : "tel_net",
        "name" : "手机上网",
        "directed" : true,
        "directedFixed" : false,
        "linkType" : "EVENT",
        "linkTypeFixed" : true,
        "sourceEntity" : "mobile_phone",
        "targetEntity" : "ip",
        "idProperty" : {
            "uuid" : "ID",
            "name" : "标识",
            "identifier" : true,
            "type" : "text",
            "index" : true,
            "multivalue" : false,
            "stored" : true,
            "analyse" : false,
            "originType" : "CUSTOM"
        },
        "properties" : [
            {
                "uuid" : "begin_time",
                "name" : "开始时间",
                "semanticType" : "datetime",
                "semanticName" : "日期时间",
                "identifier" : false,
                "type" : "datetime",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "end_time",
                "name" : "结束时间",
                "semanticType" : "datetime",
                "semanticName" : "日期时间",
                "identifier" : false,
                "type" : "datetime",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "times",
                "name" : "发生次数",
                "semanticType" : "integer",
                "semanticName" : "整数",
                "identifier" : false,
                "type" : "integer",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "mobile_phone",
                "name" : "手机",
                "semanticType" : "phone_number",
                "semanticName" : "电话号码",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "CUSTOM"
            },
            {
                "uuid" : "ip",
                "name" : "IP",
                "semanticType" : "website",
                "semanticName" : "网址",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "CUSTOM"
            }
        ],
        "semanticType" : "event_link",
        "semanticName" : "事件关系",
        "sourceRootSemanticType" : "mobile_phone",
        "targetRootSemanticType" : "ip",
        "labelTemplate" : "手机",
        "lastUpdateTime" : ISODate("2018-05-25T18:10:36.549+08:00")
    },
    {
        "uuid" : "mail_net",
        "name" : "邮件发送",
        "directed" : false,
        "directedFixed" : false,
        "linkType" : "EVENT",
        "linkTypeFixed" : true,
        "sourceEntity" : "email",
        "targetEntity" : "ip",
        "idProperty" : {
            "uuid" : "ID",
            "name" : "标识",
            "identifier" : true,
            "type" : "text",
            "index" : true,
            "multivalue" : false,
            "stored" : true,
            "analyse" : false,
            "originType" : "CUSTOM"
        },
        "properties" : [
            {
                "uuid" : "times",
                "name" : "发生次数",
                "semanticType" : "integer",
                "semanticName" : "整数",
                "identifier" : false,
                "type" : "integer",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "begin_time",
                "name" : "开始时间",
                "semanticType" : "datetime",
                "semanticName" : "日期时间",
                "identifier" : false,
                "type" : "datetime",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "end_time",
                "name" : "结束时间",
                "semanticType" : "datetime",
                "semanticName" : "日期时间",
                "identifier" : false,
                "type" : "datetime",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "email",
                "name" : "邮箱",
                "semanticType" : "email_address",
                "semanticName" : "邮箱",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : true,
                "originType" : "CUSTOM"
            },
            {
                "uuid" : "ip",
                "name" : "ip",
                "semanticType" : "website",
                "semanticName" : "网址",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "CUSTOM"
            }
        ],
        "semanticType" : "event_link",
        "semanticName" : "事件关系",
        "sourceRootSemanticType" : "email_account",
        "targetRootSemanticType" : "ip",
        "labelTemplate" : "邮件发送",
        "lastUpdateTime" : ISODate("2018-05-25T10:47:19.103+08:00")
    },
    {
        "uuid" : "event_link_aaa",
        "name" : "事件关系aaa",
        "directed" : true,
        "directedFixed" : false,
        "linkType" : "EVENT",
        "linkTypeFixed" : true,
        "sourceEntity" : "mobile_phone",
        "targetEntity" : "email",
        "idProperty" : {
            "uuid" : "ID",
            "name" : "标识",
            "identifier" : true,
            "type" : "text",
            "index" : true,
            "multivalue" : false,
            "stored" : true,
            "analyse" : false,
            "originType" : "CUSTOM"
        },
        "properties" : [
            {
                "uuid" : "times",
                "name" : "发生次数",
                "semanticType" : "integer",
                "semanticName" : "整数",
                "identifier" : false,
                "type" : "integer",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "begin_time",
                "name" : "开始时间",
                "semanticType" : "datetime",
                "semanticName" : "日期时间",
                "identifier" : false,
                "type" : "datetime",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "end_time",
                "name" : "结束时间",
                "semanticType" : "datetime",
                "semanticName" : "日期时间",
                "identifier" : false,
                "type" : "datetime",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "PT9z6xr9KvD2bjQEf",
                "name" : "aaa",
                "semanticType" : "text",
                "semanticName" : "文本",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : true,
                "originType" : "CUSTOM"
            }
        ],
        "semanticType" : "event_link",
        "semanticName" : "事件关系",
        "sourceRootSemanticType" : "mobile_phone",
        "targetRootSemanticType" : "email_account",
        "labelTemplate" : "开始时间",
        "lastUpdateTime" : ISODate("2018-05-25T18:33:34.622+08:00")
    },
    {
        "uuid" : "phone_imsi",
        "name" : "phone_imsi",
        "directed" : false,
        "directedFixed" : false,
        "linkType" : "RELATION",
        "linkTypeFixed" : true,
        "sourceEntity" : "elp_goods_phone",
        "targetEntity" : "elp_goods_phone_imsi",
        "idProperty" : {
            "uuid" : "ID",
            "name" : "标识",
            "identifier" : true,
            "type" : "text",
            "index" : true,
            "multivalue" : false,
            "stored" : true,
            "analyse" : false,
            "originType" : "CUSTOM"
        },
        "properties" : [
            {
                "uuid" : "times",
                "name" : "发生次数",
                "semanticType" : "integer",
                "semanticName" : "整数",
                "identifier" : false,
                "type" : "integer",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "begin_time",
                "name" : "开始时间",
                "semanticType" : "datetime",
                "semanticName" : "日期时间",
                "identifier" : false,
                "type" : "datetime",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "end_time",
                "name" : "结束时间",
                "semanticType" : "datetime",
                "semanticName" : "日期时间",
                "identifier" : false,
                "type" : "datetime",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "SEMANTIC"
            },
            {
                "uuid" : "phone_imsi_relation_id",
                "name" : "relation_id",
                "semanticType" : "unique_identifier",
                "semanticName" : "唯一标识",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "CUSTOM"
            },
            {
                "uuid" : "relation_phone_id",
                "name" : "phone_id",
                "semanticType" : "unique_identifier",
                "semanticName" : "唯一标识",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "CUSTOM"
            },
            {
                "uuid" : "relation_imsi_id",
                "name" : "imsi_id",
                "semanticType" : "unique_identifier",
                "semanticName" : "唯一标识",
                "identifier" : false,
                "type" : "text",
                "index" : true,
                "multivalue" : false,
                "stored" : true,
                "analyse" : false,
                "originType" : "CUSTOM"
            }
        ],
        "semanticType" : "relation_link",
        "semanticName" : "关联关系",
        "sourceRootSemanticType" : "elp_goods_phone",
        "targetRootSemanticType" : "elp_goods_phone_imsi",
        "labelTemplate" : "relation_id",
        "lastUpdateTime" : ISODate("2018-05-26T00:19:33.340+08:00")
    }
],
    "graphState" : "SCHEMA_OUT_SYNC",
    "name" : "北京模型",
    "description" : "北京模型",
    "createTime" : ISODate("2018-01-18T15:04:36.332+08:00"),
    "lastUpdateTime" : ISODate("2018-05-26T00:22:36.755+08:00")
}])